name: pushDocs

on:
  // 配置当push进入什么分支的时候执行
  push:main
    branches:gh-pages
     - main


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

     // 具体的执行步骤
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
      
      - name: Install dependencies
        run: npm install
    

      - name: Build VuePress
        run: npm run build
      
      - name: Deploy to Pages
        run: |
          cd .vitepress/dist 
          git init
          git config user.name "MountTree"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git commit -m 'deploy'
          git push -f https://MountTree:${{ secrets.ACCESS_TOKEN }}@github.com/MountTree/blog.git master:gh-pages
          cd -
